apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp
spec:
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: kubeapp
        image: imnagaraj/kubeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubeapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080

